### PR TITLE
Change MIT license name to Artex Development

### PR DESCRIPTION
**Pull request by jammehcow**
Once all contributors give their permission to change license holder, this PR will be merged into 2.0-dev.

Need permission from:
 - [x] Myself
 - [x] @AL1L 
 - [x] @mathhulk 
 - [x] @martijn-heil 
 - [ ] @hintss 
 - [x] @SwadicalRag 
 - [x] @ExplosiveNight 
 - [ ] @Development4you 

Just comment that you give approval below and I'll mark you off.

### CODE REVIEW

**Comment by mathhulk** [comment]
👍

**Comment by jammehcow** [comment]
And also @Development4you

**Comment by ExplosiveNight** [comment]
I approve! Good luck on your projects & lack of communication. Trying to be a good boy now.

**Comment by ExplosiveNight** [comment]
Sorry for lack of communication***

**Comment by AL1L** [comment]
+1

**Comment by martijn-heil** [comment]
Oh I'm fine with that, go ahead. 

The only thing that I ever contributed was the *idea 
* to make `/lukkit run` more secure, which resulted in Jammehcow giving me credit for it in a comment in the config.yml. He spelled my name wrong though, so I submitted a pull request with the good spelling if I remember correctly. Hardly something that would give me any copyrights in this project anyway.

(obviously I'm not a lawyer)
Regarding the MIT though, I'm pretty sure that technically speaking every single plugin using Bukkit* actually *has* to be GPLv3 licensed, because Bukkit itself is. Regardless, most plugins break this condition and nobody really seems to give a damn.

The old Bukkit developers (EvilSeph and others) once said (years ago) they will not carry out legal action against people who license their plugin under different licenses, but that never really carried any legal weight, and does so even less now.

 Anyway, good job that Lukkit is active again. I always loved the plugin for the ability to quickly script some very server-specific things together.

*: To clarify, by *Bukkit* I mean the API, *not* CraftBukkit which is just a implementation of Bukkit for the vanilla Minecraft server.

**Comment by AL1L** [comment]
@martijn-heil Bukkit plugins do not contain any code from the Bukkit API itself, so it doesn't have to have the same License. The plugin is injected into the JVM via Bukkit and then calls methods and stuff from the API.

**Comment by jammehcow** [comment]
Yeah, as far as I know since we aren't using the source code of Bukkit (or derivatives) then our license doesn't matter.

**Comment by martijn-heil** [comment]
It does matter actually, see [this FAQ entry from the FSF](https://www.gnu.org/licenses/gpl-faq.html#GPLAndPlugins)

Many people are not aware of these implications of Bukkit being GPLv3.

**Comment by AL1L** [comment]
> If the main program and the plugins are a single combined program then this means you must license the plug-in under the GPL or a GPL-compatible free software license and distribute it with source code in a GPL-compliant way. **A main program that is _separate from its plug-ins_ makes _no requirements_ for the plug-ins.**

Bukkit plugins are separate from the main program and therefore have no requirements for the plugin.

**Comment by SwadicalRag** [comment]
👍

**Comment by AL1L** [comment]
I think that is up for interpretation, I would say for most Bukkit plugins they should have the same license, but it really depends on the plugin.

**Comment by martijn-heil** [comment]
Pretty much all plugins except some very rare edge cases fall into this category. For example, as soon as you use the Bukkit configuration file API or use listeners then it's already intimate communication with shared data structures.

**Comment by jammehcow** [comment]
You should be able to use the MIT license with GPLv3 licensed code as it's GPL-compatible. See [here](https://www.gnu.org/licenses/license-list.html#Expat) for more info.

**Comment by jammehcow** [comment]
We also don't need permission to change copyright holder, it turns out, with the MIT license. Merging branch immediately, discussion as to licensing terms can continue here.

**Pull request merged**
